### ISSUE TITLE
Fetch chat language from language_code

### ISSUE THREAD

**Issue by yangm97** [group-butler/GroupButler#221]
Use the new (telegram) function to pick up the user’s language

`language_code = "pt-BR"`

Ref: [bot.lua#L120](https://github.com/RememberTheAir/GroupButler/blob/master/bot.lua#L120)

**Comment by NotAFile** [comment]
@yangm97 well, I might have a different locale and timezone or the group owner might have a different timezone

**Comment by yangm97** [comment]
@NotAFile the timezone is not related to the locale. 
for groups, you would fetch the chat timezone, for users you would fetch their timezone (and mark all of them accordingly)

one might argue this is barely better than throwing the UTC for everyone though
