### ISSUE TITLE
Add local time support

### ISSUE THREAD

**Issue by yangm97** [group-butler/GroupButler#223]
Right now the bot is programmed to output UTC timestamps whenever date is needed. But we should add support for timezones in order to allow further expansion of GB feature set.

* [ ]  Save/read chat timezone on database

**Comment by NotAFile** [comment]
Hm, I see this as problematic — many users might be in different timezones and I am not sure how the bot would handle that.

**Comment by yangm97** [comment]
@NotAFile 1. Default to UTC (it already does that)
2. Let users send their location (using the telegram API) or city name
3. Store the timezone on the database.

I do expect this to be implemented *after* the postgres migration though

**Comment by RememberTheAir** [comment]
@yangm97 what kind of features are you thinking about? Because right now all the time-based things the bot offers do not require to print dates
