### ISSUE TITLE
Add custom filter/banned words/regex

### ISSUE THREAD

**Issue by dogtopus** [group-butler/GroupButler#232]
I recently migrated my moderation bot from otouto to GB and I noticed that I cannot create my own message filter using regex with GB. I used this feature on otouto to filter out some obvious spam links (similar as filtering out telegram links/antilink but for different domains and patterns)

**Comment by RememberTheAir** [comment]
That's because checking if the text of each message received in a group matches a (probably) long list of words would be pretty heavy for the bot

(sorry for the late answer)

**Comment by yangm97** [comment]
I'm going to close this issue because this feature won't be developed for the reasons mentioned above.

If a pull request does show up however, while we might merge it, that feature will be disabled on the main GB and will not be officially maintained.
