### ISSUE TITLE
Log returns Nil user when using /user warn reset button

### ISSUE THREAD

**Issue by BlizzFox** [group-butler/GroupButler#234]
Title says it all. Here is a screenshot: 

[![Screenshot_2017-08-24-11-14-28.png](https://s28.postimg.org/etpbg95f1/Screenshot_2017-08-24-11-14-28.png)](https://postimg.org/image/oe8y34uqx/)

**Comment by BlizzFox** [comment]
Another rather interesting thing I've noticed is it says it only found 1 warn.

**Comment by RememberTheAir** [comment]
Yeah that's a bug I always forget to fix

> Another rather interesting thing I've noticed is it says it only found 1 warn.

That "_1_" should be replaced by something else. When you reset the warnings of someone, the bot only knows if there were some warnings of that type, but not how many. I have probably assumed that the function to delete the key that contains the number of warnings was returning the number, but i was wrong
