### ISSUE TITLE
[Bug] [Beta] "Nil" listing in dashboard settings

### ISSUE THREAD

**Issue by BlizzFox** [group-butler/GroupButler#238]
Beta bot has a "Nil" listing in dashboard when you click the settings button. Here is a screenshot:

[![Screenshot_from_2017-09-04_14-04-24.png](https://s26.postimg.org/nr6934pjt/Screenshot_from_2017-09-04_14-04-24.png)](https://postimg.org/image/an0oqfxhx/)

**Comment by yangm97** [comment]
Fixed by 330c7fcf0b3ec6cb24324b9d7c3e139425824bc7
