### ISSUE TITLE
More options for the anti-spam function.

### ISSUE THREAD

**Issue by TomTheDragon** [group-butler/GroupButler#243]
I really would like to use the anti-spam function in our chat but i dont want to kick or ban someone right away.
So it would be cool, to have an option to maybe just mute the spamming user or just stop him from posting some more, by deleting his messages.

For example: If i set an limit to 3 stickers and user A trys to post 4 stickers in a row, he can only post 3 since everything after that, gets removed by the bot.

**Comment by NotAFile** [comment]
Being able to set other options besides kick and ban is a long requested feature. Telegram supports muting now though, so there is no need to hack something together with message deletion

**Comment by RememberTheAir** [comment]
@TomTheDragon so you need something to mute someone who sends a specific number of stickers, while deleting them too?

That's already implemented in the `staging` branch, which represents [@gbreborn_bot](https://gbreborn_bot)

**Comment by AbuDabiDEL** [comment]
Arab-spam NOT deleted message! Only BAN!
HELP!

**Comment by yangm97** [comment]
Closing since the function has been implemented already.
