### ISSUE TITLE
Settings are getting deleted at a certain time

### ISSUE THREAD

**Issue by c7oud** [group-butler/GroupButler#258]
I am facing the problem, that my settings (rules, menu settings, antiflood, media, antispam...) basically all settings are getting reset to default / everything is turned off / deleted.
This happened every day at night. The bot is running on a VPS which never turns off, I am also not getting any msg that my bot restarted. 

Anybody has an idea how I can fix that?

Thanks for your help!

**Comment by Qwerty-Space** [comment]
@c7oud Have you installed, and started redis?

**Comment by c7oud** [comment]
I tried to start redis with this command $ sudo service redis-server start but I am getting the following error:
> Job for redis-server.service failed because a configured resource limit was exceeded. See "systemctl status redis-server.service" and "journalctl -xe" for details.

However I guess I was able to start redis with this command: $redis-server

The output after $sudo service redis-server status is:

> ● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: resources) since Sa 2017-12-23 18:03:27 UTC; 5s ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
  Process: 407 ExecStopPost=/bin/run-parts --verbose /etc/redis/redis-server.post-down.d (code=exited, status=0/SUCCESS)
  Process: 404 ExecStop=/bin/kill -s TERM $MAINPID (code=exited, status=0/SUCCESS)
  Process: 400 ExecStop=/bin/run-parts --verbose /etc/redis/redis-server.pre-down.d (code=exited, status=0/SUCCESS)
  Process: 396 ExecStartPost=/bin/run-parts --verbose /etc/redis/redis-server.post-up.d (code=exited, status=0/SUCCESS)
  Process: 394 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=0/SUCCESS)
  Process: 390 ExecStartPre=/bin/run-parts --verbose /etc/redis/redis-server.pre-up.d (code=exited, status=0/SUCCESS)

**Comment by yangm97** [comment]
Seems like an issue running redis, closing by inactivity.
