### ISSUE TITLE
Translating the bot

### ISSUE THREAD

**Issue by AndrewRAN** [group-butler/GroupButler#264]
Could you create a project on crowdin or getloc?.. Current way of translating it is too difficult

**Comment by yangm97** [comment]
Done: http://crowdin.com/project/group-butler/

**Comment by AndrewRAN** [comment]
Also can you make me a proofreader of Russian language?

**Comment by yangm97** [comment]
@AndrewRAN I think it’s open for suggestions but sure, what’s your nick?

**Comment by AndrewRAN** [comment]
My username there is hotmottot.1

**Comment by AndrewRAN** [comment]
@yangm97 Btw is there a hosted version of the bot? I want to check some contexts but @GroupButler_bot doesn't work...

**Comment by Qwerty-Space** [comment]
@AndrewRAN @GroupButler_Bot is online for me.

**Comment by AndrewRAN** [comment]
Hey, could you please update Russian strings?

**Comment by NotAFile** [comment]
we can sync the approved translations from Crowdin, if that is what you mean. But only

**Comment by AndrewRAN** [comment]
Yes, that's what I mean.

**Comment by AndrewRAN** [comment]
Oof, my translation was deleted again, and itsn't in the translation memory. Could you please do backups or archive them somewhere?

**Comment by NotAFile** [comment]
@AndrewRAN translations get removed if the string gets updated in the main bot. If the text is different enough that crowdin doesn't suggest the TM, you can use "search TM" to find the text again. This isn't great, but it's kind of a limitation of the crowdin platform

**Comment by AndrewRAN** [comment]
Haven't found my translation in the Search TM tab :(

**Comment by yangm97** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/4412002/44935080-bcff5980-ad45-11e8-935d-c93c3d545a69.png">

It's showing just fine for me.

**Comment by AndrewRAN** [comment]
@yangm97 now try to find my translations on Banhammer powers string.

**Comment by yangm97** [comment]
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/4412002/44943468-29597780-ad9d-11e8-8503-b8ebdc671d54.png">

Is that it? Sorry, I don't know Russian.

**Comment by yangm97** [comment]
There's two versions of that stored on TM it seems...

**Comment by AndrewRAN** [comment]
Yep, that's it but what about line wrapping there?

**Comment by NotAFile** [comment]
yeah, it looses the formatting, that's a shame. Personally, I found it relatively easy to reformat it though. I don't know if perhaps some workaround could be used to improve this.

This will hopefully be better when we separate the help files out.

**Comment by AndrewRAN** [comment]
My language sometimes resets to English in the bot what's wrong with it? I can't test my translations properly.

**Comment by yangm97** [comment]
looks like your redis instance is set to not persist data

**Comment by AndrewRAN** [comment]
So what can I do about that?
