### ISSUE TITLE
Error installing curl

### ISSUE THREAD

**Issue by ranrinc** [group-butler/GroupButler#275]
OS: Debian 9

Error running `luarocks install Lua-cURL`

```Error: Could not find expected file curl/curl.h, or curl/curl.h for CURL -- you may have to install CURL in your system and/or pass CURL_DIR or CURL_INCDIR to the luarocks command. Example: luarocks install lua-curl CURL_DIR=/usr/local```

any help?

**Comment by NotAFile** [comment]
Please read the installation instructions or the error message you just posted. You have not installed the required curl packages.

For future questions, please use the group butler group.

**Comment by ranrinc** [comment]
curl packages is installed on debian 9. I reinstalled and still no lucks on the issue.

P.S. It work without a problem on fresh install ubuntu 16.04

**Comment by NotAFile** [comment]
curl-dev too? I'll try this in a second and see if I can reproduce

**Comment by ranrinc** [comment]
@NotAFile try to install several package for curl without any luck. including adding libcurl-dev

**Comment by ranrinc** [comment]
any update?

**Comment by NotAFile** [comment]
I get the same error on debian 9.

Try installing lua-curl with apt instead

**Comment by Swiftnesses** [comment]
Same issue on the latest Ubuntu build...

**Comment by NotAFile** [comment]
Sorry, I forgot to reopen this.

**Comment by Swiftnesses** [comment]
I've tried everything I can think of, tried all curl packages, no luck... No GB :-(

**Comment by Qwerty-Space** [comment]
Which branch are you using?

**Comment by Swiftnesses** [comment]
Master, seems the most up to date according to commits?

**Comment by Swiftnesses** [comment]
I don't think it's a branch issue though TBH...

**Comment by Qwerty-Space** [comment]
I'm just saying that if you're using the master branch, you can use Docker to avoid this issue

**Comment by Swiftnesses** [comment]
That's a good point, I'm not experienced with Docker, how would I make changes to the code and apply them?

**Comment by NotAFile** [comment]
@Swiftnesses the files are mounted inside the container, so as usual.

**Comment by Qwerty-Space** [comment]
Are you on the master branch?

**Comment by Swiftnesses** [comment]
@NotAFile I can try and setup Docker, but, not sure I'll win... Any ideas what be causing this Curl error?

**Comment by NotAFile** [comment]
I don't know, but it likely involves some kind of path stuff. I have not personally investigated it.

It's probably a better idea to take extended discussions like this into chat instead of these issues though.

**Comment by Qwerty-Space** [comment]
@Swiftnesses If you join the telegram group I can help you set up Docker.

**Comment by Swiftnesses** [comment]
I'd prefer not to use docker if at all possible.

**Comment by Swiftnesses** [comment]
Thanks for the offer though @Qwerty-Space 👍

**Comment by george0884** [comment]
I fix it likes this

[https://github.com/george0884/error-could-not-find-expected-file-curl-curl.h](url)
