### ISSUE TITLE
[Questions] Anti Flood

### ISSUE THREAD

**Issue by seth-rah** [group-butler/GroupButler#279]
Hi there

Just some questions about how anti flood works when set up through the bot user

I am currently running an ubuntu server with docker and hosting the bot using that.

## 1

I have the bot set up as the following below, and I am curious as to how the sensitivity works. Is it a value on how many messages it needs a user to flood before taking action, or is it a strength value, and if the latter, how does it function.

What happened today was 10 users instant joined the channel and before it could get its usual welcome messages out, it was already being flooded.

![image](https://user-images.githubusercontent.com/2222634/36601168-14b5f15c-18bd-11e8-906b-6539ee4a0e04.png)

About 2000 messages made it into the group by about 10 users in a 2 minute timespan and only then did the bot get to banning them, so I am wondering was the sensitivity too high, or was the server just flooded with requests and the bot was struggling to keep up?

Also, not sure if worth noting that my logs seem to filled with the following, but could be related to why it took the bot 2 minutes to remove them.

![image](https://user-images.githubusercontent.com/2222634/36602835-b19530a6-18c1-11e8-8c85-16f4d43f709b.png)

## 2

Is there an anti flood option for users mass joining within 1 second of each  other? The thought is that if 3 people join within 1 second of each other that all people joining within that timeframe should be bannable.

If it does not exist, would it be possible for me to draw up a spec document and make a request for it?

## 3

Is there an option making users required to post "I agree" or something similar before they are allowed to make any other posts into the group? the message requirement could be set up with the welcome message. Any other actions can result in muting / kicking / banning the user.

**Comment by RememberTheAir** [comment]
**1.** this is in simple words how the antiflood system works:
- user sends a message
- if the message is not a service message ("_$name joined/left the group_") or an ignored object, the user counter is increased by 1. This counter is reset every 5 seconds, unless the user sends another message. If it is the case, the counter is increased again and the countdown starts again from 5 to 0
- if the user counter is higher than the value you've set from the settings, then the user is muted/kicked/banned

This means that, with the default antiflood settings, an user that sends 6 messages in 5 seconds gets punished. But also sending one message every 4 seconds for 6 times will result in a ban.

> so I am wondering was the sensitivity too high, or was the server just flooded with requests and the bot was struggling to keep up?

5/5 msgs/seconds is enough to trigger the bot during intense flood - also the minimum is 3/5 msgs/seconds, so it is really close to the lowest value possible. The bot should be pretty quick to ban people who start flooding like that. On what kind of machine are you hosting it?

> Also, not sure if worth noting that my logs seem to filled with the following, but could be related to why it took the bot 2 minutes to remove them.

Could be related, yes. That thing shouldn't happen - the bot skips ("_old update skipped_") every message that has a `date` attribute 7 seconds older than the current server time. As I said this shouldn't happen unless your bot is administrating hundreds/thousends of groups, how many groups is your bot administrating?

**2.**

> all people joining within that timeframe should be bannable

What do you mean? That the bot should ban them, or that there should be a quick way to ban them?

**3.** no but I always wanted to make the default permissions expire after some time, so, for example, admins would be able to set the bot to mute new members for x minutes after they join - similar to that Discord option to mute new members

**Comment by seth-rah** [comment]
**1**

The server is currently running on a digital ocean 5 dollar tier droplet, so it's not really a beast of a machine at all.

![image](https://user-images.githubusercontent.com/2222634/36627158-63e3c616-1947-11e8-950a-7f4e48324c49.png)

Regarding the old update skipped message, the bot is administrating 2 groups at this time, both with a member count under 100, it seems to be instant on anything, it only really seemed to have trouble because 10 people joined instantly on top of one another, it's queue might have gotten a bit too flooded and the hardware could not keep up. (updating the timer on 10 users and updating their message count within the group)

Might you have any idea as to how to fix the problem with the bot having flooded the logs with the message. Also not sure if this is noteworthy either, but the message that was being flooded is the following.

![image](https://user-images.githubusercontent.com/2222634/36627265-ea2c6326-1948-11e8-8cb4-7832193f92cf.png)

Thanks for the info on how the settings work for antiflood though, very good to know.

**2**

The idea behind this is the same as the antiflood system, but instead of counting messages, it counts users joining the group, and stores which users in an array. And each user that joined the group in the timeframe has a punishment enforced on them. When the timer expires, the array is cleared. This way 4 people joining on top of one another into a group will be punishable, in my case I will mute them and inspect the user, but for larger groups this might be more difficult to enforce.

**3**

That's a very neat idea. I look forward to it if it's something that's in the pipeline.

**Comment by yangm97** [comment]
`1.` is related to #293 

`2.` and `3.` are nice feature requests. Should have their own issues maybe?

**Comment by yangm97** [comment]
`2.` Is being tracked at #385 
`3.` is being tracket at #418
