### ISSUE TITLE
[Suggestion][Feature request] Whitelist the domains/patterns

### ISSUE THREAD

**Issue by amyodov** [group-butler/GroupButler#295]
Sometimes the group needs to whitelist some specific URLs; but sometimes they can whitelist whole friendly domains; or maybe some URL patterns.

Some simple syntax for that could use “*” and “.” wildcard symbols for url patterns. Passing “`domain.zone/*`” would then allow any possible link in this domain (and even the whole `domain.zone`).

**Comment by Qwerty-Space** [comment]
whitelisting `https://github.com/RememberTheAir/GroupButler` will also whitelist `https://github.com/RememberTheAir/GroupButler/issues/295` and everything else in there.  Whilst `https://github.com` will not be whitelisted.

**Comment by yangm97** [comment]
Closing this as it seems like an answered question.
