### ISSUE TITLE
Problem starting (via Docker, via install.sh, via manual install)

### ISSUE THREAD

**Issue by Swiftnesses** [group-butler/GroupButler#298]
Hello,

Regardless of the install method it always throws the same error upon start, I also see a number of people in Telegram reporting this.

Error: 'error loading module 'cjson' from file 'usr/local/lib/lua/5.2/cjson.so'

**Comment by Qwerty-Space** [comment]
Do `lua --version` I think. 

You could have more than one Lua version installed.

**Comment by seth-rah** [comment]
Can you verify that the directory exists for me, and if not, where does the tree stop.

Also which operating system are you doing this on?

**Comment by Swiftnesses** [comment]
Hi @seth-rah I removed the docker, but can try again later. This was the same error on all install methods, even tried Ubuntu, Mint, OSX. There's an issue with the branch I assume.

**Comment by seth-rah** [comment]
If you run this, what do you get?

```
lua -v
```

My return is "Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio"

This isn't a problem with the branch specifically, this is something that's not installed on the machine, /usr/local/lib/lua/5.2/cjson.so is not part of GroupButler, it's part of Lua

There's a possibility that Lua, even if installed, might be installed incorrectly.

**Comment by Swiftnesses** [comment]
I believe it's lua -v, and it shows one version, 5.2.4

**Comment by seth-rah** [comment]
Check for me where the following tree stops

From where can you not find the files anymore?

```
1. /usr/
2. /usr/local/
3. /usr/local/lib/
4. /usr/local/lib/lua/
5. /usr/local/lib/lua/5.2/
6. /usr/local/lib/lua/5.2/cjson.so
```

**Comment by Swiftnesses** [comment]
Number 6, the file is present...

**Comment by seth-rah** [comment]
So this means that it's possibly a permission issue that you're unable to access the file, can you try and run install.sh as root?

**Comment by Swiftnesses** [comment]
Sadly the same issue :-(

**Comment by seth-rah** [comment]
Can you try

`sudo chmod +x launch.sh`

Followed by running launch.sh again?

My only guess right now is that you don't have access to the directory the lua file is stored in.

Or it might be a problem introduced in 18.04 which 16.04 did not have, but this should not be a problem as you did say you tried this on other operating systems as well, or it could be, the kernel did change between 16.04 and 18.04, and this might be the case on all the distros you tried.

**Comment by Swiftnesses** [comment]
I've tried all that, including trying both 18.04 and 16.04...

**Comment by seth-rah** [comment]
Looks like I have run out of advice to give

I did come across this stackoverflow solution to a different problem, but should hopefully fix your problem as well.

https://stackoverflow.com/questions/39760619/lua-cannot-find-installed-luarocks-on-ubuntu

**Comment by Swiftnesses** [comment]
Tried and failed, but really appreciate the help and advice. Hopefully one of the devs can solve it - it's very easy to reproduce!

**Comment by AncalagonTheBlack** [comment]
i can confirm this. i first thought i had something misconfigured and tried to solve it for half an hour but also docker as the problem

**Comment by AncalagonTheBlack** [comment]
EDIT: You mustnt install the newest version of lua-cjson. the recent version is just 15 days old and breaks the lua_objlen function. install the older version https://luarocks.org/modules/openresty/lua-cjson/2.1.0-1 and everything works fine

**Comment by seth-rah** [comment]
Swiftnesses did Ancalagon's solution work for you too, or are you still having issues?

**Comment by Qwerty-Space** [comment]
I got this error on my clone recently, and have managed to find a workaround.
Please see this PR https://github.com/RememberTheAir/GroupButler/pull/301.

**Comment by AncalagonTheBlack** [comment]
well thats the error i already mentioned above

**Comment by Qwerty-Space** [comment]
@AncalagonTheBlack I said I found a workaround.  Look at what files I changed.

**Comment by AncalagonTheBlack** [comment]
Sorry it didnt showed that up for me on android. Sorry :3 but yeah thats how ive done it too and the workaround should be pulled asap :3

**Comment by Qwerty-Space** [comment]
Lol I didn't realise you found out too, even though it was the message above mine.  Wow.
