### ISSUE TITLE
Bot keeps stopping after a while. No Error logs.

### ISSUE THREAD

**Issue by ghost** [group-butler/GroupButler#302]
### Steps to reproduce
1. run /.launch.sh 
2. wait for a few hours
3. bot will stop working 

### Expected behaviour
Bot should keep on working if i dont halt or stop the launch script

### Actual behaviour
bot stops pulling updates and doesnt work anymore

**Operating system:** 
Debain 9 Stable

**Comment by NotAFile** [comment]
@AncalagonTheBlack not really enough info here to really do something. Can you try killing it with ctrl-c next time, I think it spit out a traceback.

**Comment by yangm97** [comment]
Closing until we have some info.
