### ISSUE TITLE
Setting "reports" to "on" in config.lua causes problems

### ISSUE THREAD

**Issue by Qwerty-Space** [group-butler/GroupButler#319]
**Describe the bug**
Setting "reports" to "on" in config.lua causes it to show as being turned on in mysettings, but not actually be on

**Steps to reproduce**
1. Go to ‘config.lua’
2. Set https://github.com/group-butler/GroupButler/blob/master/lua/config.lua#L220 to  ‘on’
3. Tell someone to report message 
4. "Reported to 0 admins"

**Expected behavior**
It should report to all admins that have started the bot

**Environment**
master branch using Docker

Commit id: 11fad48333ca81857754b44eb2afb19273364436
Debian 8 jessie

**Comment by yangm97** [comment]
Fixed by #322
