### ISSUE TITLE
[QUESTION] Private mode

### ISSUE THREAD

**Issue by MxShift** [group-butler/GroupButler#324]
Hi guys, is it possible to run Group Butler in private mode? I mean for only groups allowed by bot owner?

**Comment by Qwerty-Space** [comment]
@MxShift Yes.  In the .env file, type GB_ADMIN_MODE=true

**Comment by MxShift** [comment]
@Qwerty-Space cool, thanks you!

**Comment by Qwerty-Space** [comment]
@MxShift You can also go to botfather, and turn groups to "off"
