### ISSUE TITLE
Post update bug: bad argument #2 to 'table_insert' (position out of bounds)

### ISSUE THREAD

**Issue by seth-rah** [group-butler/GroupButler#338]
**Describe the bug**

After Upgrading the bot to the current master build on github, the bot has been stuck in a reboot loop throwing me the following error.

I have 2 bots that are both experiencing this same issue at the moment. 

The environment I am running the bot on is docker.

**Steps to reproduce**

No steps available. Upgrading the bot from a previous master build (uncertain on date) left the bot in its current loop.

If the bot starts stable, the first command it receives in DM also causes it to enter the loop

**Expected behavior**

Normal bot behavior that runs as expected.

**Screenshots**

![image](https://user-images.githubusercontent.com/2222634/42984658-f9ee7a16-8bed-11e8-9619-b49e05ee0e41.png)

```lua
groupbutler_1  | BOT RUNNING:   [@cuteButlerBot] [Cute Maid] [478056212]
groupbutler_1  |
groupbutler_1  | lua: /usr/local/share/lua/5.2/redis.lua:802: /usr/local/share/lua/5.2/redis.lua:471: bad argument #2 to 'table_insert' (position out of bounds)
groupbutler_1  | stack traceback:
groupbutler_1  |        [C]: in function 'error'
groupbutler_1  |        /usr/local/share/lua/5.2/redis.lua:802: in function 'error'
groupbutler_1  |        /usr/local/share/lua/5.2/redis.lua:480: in function 'pipeline'
groupbutler_1  |        ./lua/main.lua:85: in function 'on_msg_receive'
groupbutler_1  |        ./lua/main.lua:335: in function 'parseMessageFunction'
groupbutler_1  |        polling.lua:47: in main chunk
groupbutler_1  |        [C]: in ?
groupbutler_1  |
groupbutler_1  | BOT RUNNING:   [@cuteButlerBot] [Cute Maid] [478056212]
groupbutler_1  |
groupbutler_1  | [04:41:48]     Old update skipped:     04:41:40        8
groupbutler_1  | Cron...
groupbutler_1  |
groupbutler_1  | BOT RUNNING:   [@cuteButlerBot] [Cute Maid] [478056212]
groupbutler_1  |
groupbutler_1  | [05:14:59]     Old update skipped:     05:12:17        162
groupbutler_1  | Cron...
groupbutler_1  | lua: /usr/local/share/lua/5.2/redis.lua:764: could not connect to redis:6379 [connection refused]
groupbutler_1  | stack traceback:
groupbutler_1  |        [C]: in function 'error'
groupbutler_1  |        /usr/local/share/lua/5.2/redis.lua:802: in function 'error'
groupbutler_1  |        /usr/local/share/lua/5.2/redis.lua:764: in function </usr/local/share/lua/5.2/redis.lua:760>
groupbutler_1  |        (...tail calls...)
groupbutler_1  |        /usr/local/share/lua/5.2/redis.lua:836: in function 'connect'
groupbutler_1  |        ./lua/database.lua:3: in main chunk
groupbutler_1  |        [C]: in function 'require'
groupbutler_1  |        ./lua/methods.lua:7: in main chunk
groupbutler_1  |        [C]: in function 'require'
groupbutler_1  |        polling.lua:5: in main chunk
groupbutler_1  |        [C]: in ?
groupbutler_1  |
```

**Additional context**

I upgraded the bot in hopes of fixing an old update skipped issue I have with the bot, that's been persisting for a while now. In my attempt to update it appears something else broke.

**Environment**

Self Hosted

Commit id: `e77fea13930586898d10956be41c7f08bc41fe02`
OS: Ubuntu 16.04
Docker: Building the container with docker from git

**Comment by yangm97** [comment]
The bot uses LUA 5.1, your error log indicates it’s using LUA 5.2. Please use the official Dockerfile or pull from the official repo: `docker pull groupbutler/groupbutler:dev` (for master branch).

**Comment by seth-rah** [comment]
Thanks for the input

Is this a recent change? The bot was running fine for a few months on upgrades, and I had to upgrade my LUA version a while ago to fix a luarocks issue that was occurring. 

Also was there always an image, I remember looking for one when I installed the bot originally and I couldn't find the image? I found it now however.

**Comment by NotAFile** [comment]
@seth-rah You are using a lua 5.2 container, however lua 5.2 is currently broken by a dependency. The current Dockerfile should build with lua 5.1

**Comment by NotAFile** [comment]
It's a somewhat recent change. We have been lua 5.1 for a while now, but a change I added recently used a lua 5.1 incompatible library feature (lua-redis pipelining) in the main loop for the first time. This is the cause of the error message above. There are pull-requests to lua-redis that solve this, but it is unmaintained.

**Comment by yangm97** [comment]
The bot used to run on LUA 5.2 but both lua-cjson and redis-lua are having issues with LUA 5.2+, besides the upcoming web hooks mode is LUAjit based so it only makes sense for us to move to LUA 5.1. 

And yes, official docker images are a new addition.
