### ISSUE TITLE
Error after using bash install.sh

### ISSUE THREAD

**Issue by fabston** [group-butler/GroupButler#364]
Hello,

I am getting the following error after trying to start the bot with ./launch.sh

`lua: ./lua/groupbutler/config.lua:2: module 'cjson' not found:
	no field package.preload['cjson']
	no file './lua/cjson.lua'
	no file './lua/vendor/cjson.lua'
	no file './cjson.lua'
	no file '/usr/local/share/lua/5.1/cjson.lua'
	no file '/usr/local/share/lua/5.1/cjson/init.lua'
	no file '/usr/local/lib/lua/5.1/cjson.lua'
	no file '/usr/local/lib/lua/5.1/cjson/init.lua'
	no file '/usr/share/lua/5.1/cjson.lua'
	no file '/usr/share/lua/5.1/cjson/init.lua'
	no file './cjson.so'
	no file '/usr/local/lib/lua/5.1/cjson.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/cjson.so'
	no file '/usr/lib/lua/5.1/cjson.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	./lua/groupbutler/config.lua:2: in main chunk
	[C]: in function 'require'
	./lua/groupbutler/plugins.lua:1: in main chunk
	[C]: in function 'require'
	./polling.lua:14: in main chunk
	[C]: ?`

**Comment by NotAFile** [comment]
@fabston you have not sucessfully installed cjson

**Comment by fabston** [comment]
Thanks for the reply. Isnt the install.sh file taking care of that?

**Comment by fabston** [comment]
Besides that error I also keep on getting:

`lua: ./lua/vendor/resty/redis.lua:31: module 'resty.socket' not found:
	no field package.preload['resty.socket']
	no file './lua/resty/socket.lua'
	no file './lua/vendor/resty/socket.lua'
	no file './resty/socket.lua'
	no file '/usr/local/share/lua/5.1/resty/socket.lua'
	no file '/usr/local/share/lua/5.1/resty/socket/init.lua'
	no file '/usr/local/lib/lua/5.1/resty/socket.lua'
	no file '/usr/local/lib/lua/5.1/resty/socket/init.lua'
	no file '/usr/share/lua/5.1/resty/socket.lua'
	no file '/usr/share/lua/5.1/resty/socket/init.lua'
	no file './resty/socket.so'
	no file '/usr/local/lib/lua/5.1/resty/socket.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/resty/socket.so'
	no file '/usr/lib/lua/5.1/resty/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/resty.so'
	no file '/usr/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	./lua/vendor/resty/redis.lua:31: in function <./lua/vendor/resty/redis.lua:25>
	./lua/vendor/resty/redis.lua:34: in main chunk
	[C]: in function 'require'
	./lua/groupbutler/main.lua:5: in main chunk
	[C]: in function 'require'
	./polling.lua:15: in main chunk
	[C]: ?`

**Comment by fabston** [comment]
I also googled `resty.socket` can't really find anything useful...

**Comment by fabston** [comment]
Was able to solve the issue in the telegram channel. Thanks.

**Comment by NotAFile** [comment]
yeah install.sh is not up to date

**Comment by lutsifer** [comment]
Well I installed the master branch so... it should be this:
https://github.com/group-butler/GroupButler/blob/master/install.sh

**Comment by lutsifer** [comment]
Actually I followed this one (same thing):
```
# Tested on Ubuntu 16.04

$ wget https://raw.githubusercontent.com/group-butler/GroupButler/master/install.sh
$ bash install.sh
```
