### ISSUE TITLE
Bot Doesn't Reply After Generated A New Pinned Message

### ISSUE THREAD

**Issue by Fathurhoho** [group-butler/GroupButler#365]
**Bug desc**
Bot doesn't reply or notif us if new pin message has been generated.
Here is a short video [telegraph](https://telegra.ph/file/c9c4b181fb9621db40fdd.mp4)

**Steps to reproduce**
Generate new pin with `/pin <new pin message>.`

**Expected behavior**
Bot should reply a message about new pin message has been generated.

Bot version: @GBReborn_bot | Beta

**Comment by yangm97** [comment]
`/pin` behavior has been modified, it will automatically pin the message.
