### ISSUE TITLE
How to setup mute time?

### ISSUE THREAD

**Issue by habrauser** [group-butler/GroupButler#376]
Now bot is muting users forever :(

I want to mute for 1 day or for 1 week. How it possible to set?

**Comment by Qwerty-Space** [comment]
Do you mean default permissions?
If so, that does not have a time limit, it is permanent.  (Unless changed manually)

**Comment by habrauser** [comment]
I saw this discussion:
https://github.com/group-butler/GroupButler/issues/343

One guy give a commit to do this:
https://github.com/riskey95/GroupButler/commit/dc56eb579a96402506b0d78995fb9212c6322b94

**Comment by Qwerty-Space** [comment]
The PR (#345) hasn't been merged yet

**Comment by habrauser** [comment]
Very sad situation. It would be great to have possibilities for temporary mute. Sometimes old users post links and bot mutes them permanently :(

**Comment by Qwerty-Space** [comment]
Yeah true.

It seems like we're finished here, do you mind if I close the issue?
