### ISSUE TITLE
Error when i click on button 🔄 Refresh Cahche after command #cache

### ISSUE THREAD

**Issue by devdeen** [group-butler/GroupButler#377]
groupbutler_1  | 2018/09/24  [ERROR]: An #error occurred.
groupbutler_1  | ./lua/groupbutler/plugins/users.lua:229: attempt to perform arithmetic on field 'adminlist' (a ni                  l value)
groupbutler_1  | stack traceback:
groupbutler_1  |        ./lua/groupbutler/plugins/users.lua:229: in function <./lua/groupbutler/plugins/users.lua:                  201>
groupbutler_1  |        (tail call): ?
groupbutler_1  |        [C]: in function 'xpcall'
groupbutler_1  |        ./lua/groupbutler/main.lua:186: in function 'on_msg_receive'
groupbutler_1  |        ./lua/groupbutler/main.lua:314: in function 'process'
groupbutler_1  |        polling.lua:61: in function <polling.lua:46>
groupbutler_1  |        [C]: in function 'pcall'
groupbutler_1  |        polling.lua:81: in main chunk
groupbutler_1  |        [C]: ?

**Comment by yangm97** [comment]
This has been fixed before you made this issue... try pulling the latest version.

Also please fill the fields from the issue template (like commit hash) so we don't have to guess what is happening.
