### ISSUE TITLE
Log Channel Lang Changes Randomly

### ISSUE THREAD

**Issue by Fathurhoho** [group-butler/GroupButler#381]
Our log channel language changes randomly when #new_member (or might be happen with another even also).

I did not changed the language both in group and bot. 
Our log channel link: https://t.me/joinchat/AAAAAEOk8YGR_buHEest6Q

**Comment by NotAFile** [comment]
sounds like a race condition with the current language value...

**Comment by yangm97** [comment]
Duplicate of #361
