### ISSUE TITLE
A button does not open

### ISSUE THREAD

**Issue by mmmTelegram** [group-butler/GroupButler#398]
./lua/groupbutler/utilities.lua:613: bad argument #2 to 'format' (string expected, got nil)
stack traceback:
        [C]: in function 'format'
        ./lua/groupbutler/utilities.lua:613: in function 'getSettings'
        ./lua/groupbutler/plugins/dashboard.lua:130: in function <./lua/groupbutler/plugins/dashboard.lua:106>
        (tail call): ?
        [C]: in function 'xpcall'
        ./lua/groupbutler/main.lua:186: in function 'on_msg_receive'
        ./lua/groupbutler/main.lua:314: in function 'process'
        ./polling.lua:65: in function <./polling.lua:50>
        [C]: in function 'pcall'
        ./polling.lua:86: in main chunk
        [C]: ?
en_GB
![2018-11-09 01_38_22-telegram 28322](https://user-images.githubusercontent.com/33640844/48234050-9a7e6200-e3c0-11e8-9217-ebe67f41ea63.png)

**Comment by yangm97** [comment]
Which commit hash and which command?

**Comment by yangm97** [comment]
Fixed by 330c7fcf0b3ec6cb24324b9d7c3e139425824bc7

**Comment by mmmTelegram** [comment]
fixed
