### ISSUE TITLE
The /snap command returns an error

### ISSUE THREAD

**Issue by mmmTelegram** [group-butler/GroupButler#399]
2018/11/10 23:16:02 [ERROR]: An #error occurred.
./lua/vendor/telegram-bot-api/methods.lua:104: attempt to call field 'log' (a nil value)
stack traceback:
        ./lua/vendor/telegram-bot-api/methods.lua:104: in function <./lua/vendor/telegram-bot-api/methods.lua:69>
        (tail call): ?
        ./lua/groupbutler/plugins/backup.lua:115: in function <./lua/groupbutler/plugins/backup.lua:93>
        (tail call): ?
        [C]: in function 'xpcall'
        ./lua/groupbutler/main.lua:186: in function 'on_msg_receive'
        ./lua/groupbutler/main.lua:314: in function 'process'
        ./polling.lua:65: in function <./polling.lua:50>
        [C]: in function 'pcall'
        ./polling.lua:86: in main chunk
        [C]: ?
en_GB

**Comment by yangm97** [comment]
Fixed by bf4f6faf3ede63a07a7ef7e31004263935939fd3
