### ISSUE TITLE
Add Caption + GIF image as Welcome message for new member

### ISSUE THREAD

**Issue by andreszerocross** [group-butler/GroupButler#425]
**Is your feature request related to a problem? Please describe.**
I need to use GIF + Word as welcome message. For now, we only can use GIF as welcome message and can't add caption after it. eg,, reply GIF with "/welcome".

**Describe the solution you'd like**
I need we can reply the GIF image with "/welcome blablablablbal". At another bot (maybe unofficial Group Butler) we can use this feature. See this image 
![image](https://user-images.githubusercontent.com/9614101/51013092-35e3ad00-1593-11e9-90d7-97560c046ddc.png)

**Comment by yangm97** [comment]
Closing in favour of #431
