### ISSUE TITLE
Feature request: Delete posts of bots and Ban bot inviters

### ISSUE THREAD

**Issue by hossaink** [group-butler/GroupButler#429]
1. The GroupButler has this great feature that kicks any bot; the problem is in the milliseconds-gap between adding the spammer bot and GroupButler kicking it; the spammer sometimes sends some posts that require manual deletion.
2. Moreover, if it was possible to ban the users who add bots to the group immediately; it would be great.

**Comment by NotAFile** [comment]
bots can not see other bots messages

**Comment by hossaink** [comment]
Thanks for the comment... Interesting limitation by Telegram!
How about the second feature, kicking the one who adds a bot, is it feasible?

**Comment by NotAFile** [comment]
I recall this already being a feature

**Comment by alim1369** [comment]
I didn't find this feature. it is also good if you remove or mute the parent hierarchy of the robot

**Comment by alim1369** [comment]
I have a suggestion for finding the id of messages from other robots.
each message in super groups have an incremental id so if you find a message which the last id is different it means that the message is for the robot and you can remove it.

**Comment by alim1369** [comment]
I checked this method and it is not possible to remove other robot's message

**Comment by yangm97** [comment]
Dupe of #385
