### ISSUE TITLE
/warn [kick/ban]  to set the setting for kick or ban don't work

### ISSUE THREAD

**Issue by efred** [group-butler/GroupButler#435]
Hello,
in the readme.md is noted:

> /warn [kick/ban] | choose what to do when the max number of warns is reached

But the command "/warn ban" or "/warn kick" don't work, to set if they should be banned or kicked, at reaching the maximum warns.
It always shows this message:

> I've never seen this user before.
> This command works by reply, username, user ID or text mention.
> If you're using it by username and want to teach me who the user is, forward me one of their messages

**Comment by seth-rah** [comment]
You're misusing the command.

`/warn @User` or `/warn`  by replying to a message you wish to have the owner of warned.

The readme refers to the settings of the bot itself, whether you wish to kick or ban the user after the maximum number of warns have been reached.

**Comment by Qwerty-Space** [comment]
Issue seems resolved
