### ISSUE TITLE
File Support For Welcome Messages

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [group-butler/GroupButler#439]
**Is your feature request related to a problem? Please describe.**

Tried setting a welcome message tied to a gif (Send the gif with a caption for the welcome message) and it doesn't send the gif when people join, only sends the text. 

**Describe the solution you'd like**

Want to see the ability to post a file (Gif/Mp4) and add a caption, and set the welcome bot to send that file with the caption as the welcome message, not just the caption.

**Additional context**

**Screenshot:** https://b.catgirlsare.sexy/MPUF.png

**Comment by Qwerty-Space** [comment]
Because you're supposed to do it like this:
![image](https://user-images.githubusercontent.com/6967592/64068822-82205200-cc35-11e9-8f54-6b80f56db029.png)
