### ISSUE TITLE
Some admins can’t use extra triggers

### ISSUE THREAD

**Issue by theresavs** [group-butler/GroupButler#440]
I’m a group owner and set up some extra triggers but some admins can’t active the triggers but some can. I’ve set the permissions for all the admins to be the same and Group Butler is an admin as well.
The extra setting is set to everyone but my admin says the response to the trigger gets sent to him thru private chat.  
![3ABE31CA-B81F-4455-8BB2-2CFD0A033F65](https://user-images.githubusercontent.com/17341819/65822661-e0bcf980-e1fc-11e9-80a4-7be01bb72d3d.jpeg)

**Comment by theresavs** [comment]
My admin has tried stopping and starting the bot and still no luck.

**Comment by Qwerty-Space** [comment]
As the owner, do `/cache`

**Comment by theresavs** [comment]
Thank you! That totally worked!
