### ISSUE TITLE
Is it possible to make it work in channels?

### ISSUE THREAD

**Issue by rustcat** [group-butler/GroupButler#442]
There are many things I like about GroupButler on Telegram.  However, it does not work (duh!) in channels currently.  Is there a simple way for me to make this happen?  

In general, I'm a bit puzzled why the bots I need work either in channels or groups but not both?  Are these 2 so different?

Thanks for any help.  Cheers. 

Joe

**Comment by Qwerty-Space** [comment]
There is no need for it to work in channels.
Channels are a blogging medium, only those approved by the owner can post.  Whereas groups are for people to just join and chat.
