### ISSUE TITLE
Is not working.

### ISSUE THREAD

**Issue by huezo** [group-butler/GroupButler#446]
This setting is not working in @GroupButler_bot

![Captura de pantalla de 2020-03-29 10-23-15](https://user-images.githubusercontent.com/15940634/77854390-57848080-71a7-11ea-83ce-35837a6cb968.png)

**Comment by tebicap** [comment]
There are many functions that are not working, like /extra commands, etc

**Comment by Qwerty-Space** [comment]
Should be working now
