### ISSUE TITLE
Message forwards trigger media warning

### ISSUE THREAD

**Issue by TotallyNotElite** [group-butler/GroupButler#450]
**Describe the bug**
Forwarded messages trigger media warnings for seemingly no reason.

**Steps to reproduce**
1. Forward a message to a group managed by the bot (Example: https://t.me/sag_bot_chat)
2. Receive media warning

**Expected behavior**
The user should not get a warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/38938720/84116103-816fe400-aa2f-11ea-857d-e81b923720ea.png)

**Additional context**
This started happening overnight without any changes to the groupbutler configuration.

**Environment**
@GroupButler_bot

**Comment by wefanqs** [comment]
+1 having the same issue in my group. Verified antispam and media settings, all allowed

**Comment by Qwerty-Space** [comment]
Unfortunately this was a side-effect of fixing the bug described in #448, it is being worked on right now and should be fixed shortly.

**Comment by Qwerty-Space** [comment]
Fixed #449
