### ISSUE TITLE
silent configuration

### ISSUE THREAD

**Issue by aristosv** [group-butler/GroupButler#462]
I recently started using Group Butler in Telegram, and I was wondering if I could configure it without having to send commands in the group. I don't want everyone in the group seeing the commands I sent to the bot. Is this possible?

**Comment by Qwerty-Space** [comment]
@aristosv No, but you could get a bot to delete commands

**Comment by aristosv** [comment]
Can this be automated? For example, I sent a command, the bot gets it, and then automatically deletes it?

Because I can manually delete commands in the group anyway, I just have to do it manually.

**Comment by Qwerty-Space** [comment]
@aristosv https://t.me/AntiCommandBot

**Comment by aristosv** [comment]
thank you
